name: AI-Endo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.19.5
  - pandas=1.1.5
  - python=3.6.13
  - pytorch=1.10.2
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - setproctitle=1.2.2
  - tensorboard=2.6.0
  - torchvision=0.11.3
  - tqdm=4.63.0=pyhd3eb1b0_0
  - pip:
    - albumentations==1.1.0
    - imageio==2.15.0
    - matplotlib==3.3.4
    - networkx==2.5.1
    - opencv-contrib-python==4.6.0.66
    - pillow==8.4.0
    - scikit-image==0.17.2
    - yacs==0.1.8
